### ISSUE TITLE
spam vs span

### ISSUE THREAD

**Issue by phact** [FundacionSantaRita/PROYECTO-SEMAFORO-#20]
![image](https://user-images.githubusercontent.com/1313220/82099946-8b275580-96d6-11ea-91a1-a15cf47c323c.png)

**Comment by FundacionSantaRita** [comment]
Solucionado

**Comment by phact** [comment]
https://github.com/FundacionSantaRita/semaforo/commit/b96867c9c2c9cf60aa880f2736e09787d5de201b
